version: '3'

services:

  mysql:
    image: percona/percona-server:8.0.20
    container_name: example_mysql
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password' ]
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_USER=example
      - MYSQL_DATABASE=example
      - MYSQL_PASSWORD=
      - TZ=Europe/Kiev
    ports:
      - 4423:3306
    volumes:
      - example_mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: example_phpmyadmin
    environment:
      - PMA_HOST=example_mysql
      - UPLOAD_LIMIT=209715200 # 200 mb
    ports:
      - 8083:80

volumes:
  example_mysql_data:
