site_name: API service based on Laravel
site_url: http://127.0.0.1:8000/docs
docs_dir: files
use_directory_urls: true
theme: readthedocs
nav:
  - Home: index.md
  - Support: support.md
copyright: '&copy; Owner Name, [year]'
strict: true
plugins: [ ]
